### ISSUE TITLE
Weird file beginning on Windows 10

### ISSUE THREAD

**Issue by petrmanek** [mandreyel/mio#41]
Hi all,

I've just ported my (previously Linux-only) C++ program to Windows and noticed a weird bug: Any file opened through mio has the same 3 bytes in the beginning which cause my program to crash.

Here's a sample of my usage:

```cpp
mio::mmap_source mmap{"path/to/my/file.txt"};
std::string beginning{mmap.cbegin(), 200};
std::cout << beginning << std::endl;
```

This code is supposed to print the first 200 characters of the file (which is assumed to have hundreds of MBs in size). Instead, the first 3 printed characters are just pure gibberish, and then the file goes on as expected.

Using `open()` and `read()`, I've verified that those bytes are not actually present in the read file. I've also tried it with multiple files to make sure this is something systematic. My current conclusion is that this problem must be caused somewhere within mio. The only workaround that works for me now is to simply start reading at `mmap.cbegin() + 3`.

Here's my toolchain:

 - Windows 10 x64
 - CMake 3.0
 - Visual Studio 2017 (15)
 - MSVC 19
 - CMAKE_CXX_STANDARD 14

Note that the same code has worked transparently without workarounds on Linux for the last several months.

Thank you for investigating this weird behavior!

**Comment by mandreyel** [comment]
@petrmanek Thank you for reporting this, I am really sorry for the inconvenience. I am somewhat snowed under but I will try to look into this ASAP.

**Comment by petrmanek** [comment]
@mandreyel No problem. If there's any more info I can provide, feel free to let me know.

**Comment by mandreyel** [comment]
@petrmanek I pushed some changes but I honestly doubt they are related to this. Still, if you could try it at your earliest convenience and report back, that'd be great.

**Comment by petrmanek** [comment]
@mandreyel Sure. I'm going to have access to the Windows machine again tomorrow. Will let you know.

**Comment by petrmanek** [comment]
@mandreyel I have just tried again with 88e0263b075b832e78b9a36df58575a96ffe5e7d. The problem still persists.

I attach a print screen from my last attempt where I tried to print the first 200 characters of the file. The first three characters `´╗┐` which appeared the last time were displayed now as well.

![screen](https://user-images.githubusercontent.com/1297382/54288717-36ef8580-45a8-11e9-9c21-cba291954d0a.png)

**Comment by mandreyel** [comment]
@petrmanek Thank you for testing it. This is really strange, I'm at a loss as to what is going on. I won't have a Windows machine foreseeably until next week, so I won't be able to reproduce this until then.
Would you perhaps be willing to look into debugging this on Windows until then, and maybe send a PR if you find it? It would be greatly appreciated.

**Comment by patrick--** [comment]
This looks like the byte order mark for UTF8. I've seen this type of problem in other contexts. 

https://superuser.com/questions/769601/weird-characters-%C2%B4-at-the-start-of-a-batch-file

**Comment by Wunkolo** [comment]
> This looks like the byte order mark for UTF8. I've seen this type of problem in other contexts.
I would have thought it might have been some 4-byte alignment padding thing but this looks like it's precisely it.

**Comment by petrmanek** [comment]
@mandreyel I'll try to look into it, although I make no promises. As a Linux-based person, debugging on Win32 API is a bit alien to me.

@patrick-- You're right. I've just verified in Notepad++ that the file is encoded in "UTF-8 BOM" which makes sense to me as it was originally produced by a C# program. Interestingly enough, I've read the very same file on Linux distributions and never encountered BOM bytes until now. How could that be possible if the file is mapped to memory byte-by-byte?

**Comment by mandreyel** [comment]
Thanks @patrick-- and @Wunkolo for the input. I don't have much experience with Windows either, but it looks like this isn't a mio related issue after all, correct?

**Comment by petrmanek** [comment]
@mandreyel The only question now is whether mio treats UTF-8 files with BOM differently in Windows compared to Linux. Since the file contents match, I would have expected the same behavior on both platforms. So, either Linux swallows the BOM bytes for some reason, or Windows doesn't.

**Comment by mandreyel** [comment]
@petrmanek mio simply maps a file into memory, it doesn't do any processing on it past that. As per the above link, it seems that using a BOM mark for utf-8 is discouraged for this reason, so I'd say this issue should be solved by using a different encoding when writing the file.

**Comment by petrmanek** [comment]
@mandreyel I understand that and concur with your assessment -- it's likely that mio has nothing to with the problem after all. The mistake was trusting STL's implementation of `std::string` to print the file contents, which on Linux seems to handle BOM correctly but on Windows treats it as regular "characters".

My thanks go to everyone who contributed to this discussion. Hope I haven't wasted too much of your time. On the upside, I've at least learned something new about BOMs and UTF-8. Closing.

**Comment by mandreyel** [comment]
I was unaware of this too, so I also learned something :)

Thanks everyone!
